/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmployeeRole = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'staff' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmployeeStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Time = IDL.Int;
export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'status' : EmployeeStatus,
  'salary' : IDL.Nat,
  'joinDate' : Time,
  'name' : IDL.Text,
  'role' : EmployeeRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
});
export const PayrollRecord = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'deductions' : IDL.Nat,
  'netPay' : IDL.Nat,
  'employeeId' : IDL.Nat,
  'allowances' : IDL.Nat,
  'basicSalary' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'employeeId' : IDL.Nat,
});
export const Department = IDL.Record({
  'id' : IDL.Nat,
  'headName' : IDL.Text,
  'name' : IDL.Text,
});
export const AttendanceStatus = IDL.Variant({
  'halfDay' : IDL.Null,
  'present' : IDL.Null,
  'late' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'status' : AttendanceStatus,
  'date' : Time,
  'employeeId' : IDL.Nat,
});
export const LeaveStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const LeaveType = IDL.Variant({
  'sick' : IDL.Null,
  'annual' : IDL.Null,
  'maternity' : IDL.Null,
  'casual' : IDL.Null,
});
export const LeaveRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : LeaveStatus,
  'endDate' : Time,
  'employeeId' : IDL.Nat,
  'comments' : IDL.Text,
  'leaveType' : LeaveType,
  'startDate' : Time,
  'reason' : IDL.Text,
});
export const Stats = IDL.Record({
  'totalEmployees' : IDL.Nat,
  'departments' : IDL.Nat,
  'pendingLeaveRequests' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDepartment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, EmployeeRole, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addPayrollRecord' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'approveLeaveRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllPayrollRecords' : IDL.Func([], [IDL.Vec(PayrollRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
  'getEmployeeAttendance' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getLeaveRequestsByEmployee' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaveRequest)],
      ['query'],
    ),
  'getPayrollByEmployee' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PayrollRecord)],
      ['query'],
    ),
  'getPendingLeaveRequests' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([IDL.Nat, Time, AttendanceStatus], [], []),
  'rejectLeaveRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLeaveRequest' : IDL.Func(
      [IDL.Nat, Time, Time, LeaveType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateEmployee' : IDL.Func([IDL.Nat, Employee], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmployeeRole = IDL.Variant({
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'staff' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmployeeStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Time = IDL.Int;
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'status' : EmployeeStatus,
    'salary' : IDL.Nat,
    'joinDate' : Time,
    'name' : IDL.Text,
    'role' : EmployeeRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  const PayrollRecord = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'deductions' : IDL.Nat,
    'netPay' : IDL.Nat,
    'employeeId' : IDL.Nat,
    'allowances' : IDL.Nat,
    'basicSalary' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'employeeId' : IDL.Nat });
  const Department = IDL.Record({
    'id' : IDL.Nat,
    'headName' : IDL.Text,
    'name' : IDL.Text,
  });
  const AttendanceStatus = IDL.Variant({
    'halfDay' : IDL.Null,
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'status' : AttendanceStatus,
    'date' : Time,
    'employeeId' : IDL.Nat,
  });
  const LeaveStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const LeaveType = IDL.Variant({
    'sick' : IDL.Null,
    'annual' : IDL.Null,
    'maternity' : IDL.Null,
    'casual' : IDL.Null,
  });
  const LeaveRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : LeaveStatus,
    'endDate' : Time,
    'employeeId' : IDL.Nat,
    'comments' : IDL.Text,
    'leaveType' : LeaveType,
    'startDate' : Time,
    'reason' : IDL.Text,
  });
  const Stats = IDL.Record({
    'totalEmployees' : IDL.Nat,
    'departments' : IDL.Nat,
    'pendingLeaveRequests' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDepartment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, EmployeeRole, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addPayrollRecord' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'approveLeaveRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllPayrollRecords' : IDL.Func([], [IDL.Vec(PayrollRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
    'getEmployeeAttendance' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getLeaveRequestsByEmployee' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaveRequest)],
        ['query'],
      ),
    'getPayrollByEmployee' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PayrollRecord)],
        ['query'],
      ),
    'getPendingLeaveRequests' : IDL.Func(
        [],
        [IDL.Vec(LeaveRequest)],
        ['query'],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([IDL.Nat, Time, AttendanceStatus], [], []),
    'rejectLeaveRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLeaveRequest' : IDL.Func(
        [IDL.Nat, Time, Time, LeaveType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateEmployee' : IDL.Func([IDL.Nat, Employee], [], []),
  });
};

export const init = ({ IDL }) => { return []; };