/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'status' : AttendanceStatus,
  'date' : Time,
  'employeeId' : bigint,
}
export type AttendanceStatus = { 'halfDay' : null } |
  { 'present' : null } |
  { 'late' : null } |
  { 'absent' : null };
export interface Department {
  'id' : bigint,
  'headName' : string,
  'name' : string,
}
export interface Employee {
  'id' : bigint,
  'status' : EmployeeStatus,
  'salary' : bigint,
  'joinDate' : Time,
  'name' : string,
  'role' : EmployeeRole,
  'email' : string,
  'phone' : string,
  'department' : string,
}
export type EmployeeRole = { 'admin' : null } |
  { 'teacher' : null } |
  { 'staff' : null };
export type EmployeeStatus = { 'active' : null } |
  { 'inactive' : null };
export interface LeaveRequest {
  'id' : bigint,
  'status' : LeaveStatus,
  'endDate' : Time,
  'employeeId' : bigint,
  'comments' : string,
  'leaveType' : LeaveType,
  'startDate' : Time,
  'reason' : string,
}
export type LeaveStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type LeaveType = { 'sick' : null } |
  { 'annual' : null } |
  { 'maternity' : null } |
  { 'casual' : null };
export interface PayrollRecord {
  'month' : bigint,
  'year' : bigint,
  'deductions' : bigint,
  'netPay' : bigint,
  'employeeId' : bigint,
  'allowances' : bigint,
  'basicSalary' : bigint,
}
export interface Stats {
  'totalEmployees' : bigint,
  'departments' : bigint,
  'pendingLeaveRequests' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'employeeId' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDepartment' : ActorMethod<[string, string], bigint>,
  'addEmployee' : ActorMethod<
    [string, string, string, EmployeeRole, string, bigint],
    bigint
  >,
  'addPayrollRecord' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'approveLeaveRequest' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEmployee' : ActorMethod<[bigint], undefined>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllPayrollRecords' : ActorMethod<[], Array<PayrollRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDepartments' : ActorMethod<[], Array<Department>>,
  'getEmployee' : ActorMethod<[bigint], [] | [Employee]>,
  'getEmployeeAttendance' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getLeaveRequestsByEmployee' : ActorMethod<[bigint], Array<LeaveRequest>>,
  'getPayrollByEmployee' : ActorMethod<[bigint], Array<PayrollRecord>>,
  'getPendingLeaveRequests' : ActorMethod<[], Array<LeaveRequest>>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[bigint, Time, AttendanceStatus], undefined>,
  'rejectLeaveRequest' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLeaveRequest' : ActorMethod<
    [bigint, Time, Time, LeaveType, string],
    bigint
  >,
  'updateEmployee' : ActorMethod<[bigint, Employee], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];