/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Stats {
    totalEmployees: bigint;
    departments: bigint;
    pendingLeaveRequests: bigint;
}
export interface PayrollRecord {
    month: bigint;
    year: bigint;
    deductions: bigint;
    netPay: bigint;
    employeeId: bigint;
    allowances: bigint;
    basicSalary: bigint;
}
export interface Department {
    id: bigint;
    headName: string;
    name: string;
}
export interface LeaveRequest {
    id: bigint;
    status: LeaveStatus;
    endDate: Time;
    employeeId: bigint;
    comments: string;
    leaveType: LeaveType;
    startDate: Time;
    reason: string;
}
export interface Employee {
    id: bigint;
    status: EmployeeStatus;
    salary: bigint;
    joinDate: Time;
    name: string;
    role: EmployeeRole;
    email: string;
    phone: string;
    department: string;
}
export interface AttendanceRecord {
    status: AttendanceStatus;
    date: Time;
    employeeId: bigint;
}
export interface UserProfile {
    name: string;
    employeeId: bigint;
}
export enum AttendanceStatus {
    halfDay = "halfDay",
    present = "present",
    late = "late",
    absent = "absent"
}
export enum EmployeeRole {
    admin = "admin",
    teacher = "teacher",
    staff = "staff"
}
export enum EmployeeStatus {
    active = "active",
    inactive = "inactive"
}
export enum LeaveStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum LeaveType {
    sick = "sick",
    annual = "annual",
    maternity = "maternity",
    casual = "casual"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDepartment(name: string, headName: string): Promise<bigint>;
    addEmployee(name: string, email: string, phone: string, role: EmployeeRole, department: string, salary: bigint): Promise<bigint>;
    addPayrollRecord(employeeId: bigint, month: bigint, year: bigint, basicSalary: bigint, allowances: bigint, deductions: bigint, netPay: bigint): Promise<void>;
    approveLeaveRequest(id: bigint, comments: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteEmployee(id: bigint): Promise<void>;
    getAllEmployees(): Promise<Array<Employee>>;
    getAllPayrollRecords(): Promise<Array<PayrollRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDepartments(): Promise<Array<Department>>;
    getEmployee(id: bigint): Promise<Employee | null>;
    getEmployeeAttendance(employeeId: bigint): Promise<Array<AttendanceRecord>>;
    getLeaveRequestsByEmployee(employeeId: bigint): Promise<Array<LeaveRequest>>;
    getPayrollByEmployee(employeeId: bigint): Promise<Array<PayrollRecord>>;
    getPendingLeaveRequests(): Promise<Array<LeaveRequest>>;
    getStats(): Promise<Stats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAttendance(employeeId: bigint, date: Time, status: AttendanceStatus): Promise<void>;
    rejectLeaveRequest(id: bigint, comments: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitLeaveRequest(employeeId: bigint, startDate: Time, endDate: Time, leaveType: LeaveType, reason: string): Promise<bigint>;
    updateEmployee(id: bigint, employee: Employee): Promise<void>;
}
import type { AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, Employee as _Employee, EmployeeRole as _EmployeeRole, EmployeeStatus as _EmployeeStatus, LeaveRequest as _LeaveRequest, LeaveStatus as _LeaveStatus, LeaveType as _LeaveType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDepartment(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDepartment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDepartment(arg0, arg1);
            return result;
        }
    }
    async addEmployee(arg0: string, arg1: string, arg2: string, arg3: EmployeeRole, arg4: string, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(arg0, arg1, arg2, to_candid_EmployeeRole_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(arg0, arg1, arg2, to_candid_EmployeeRole_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async addPayrollRecord(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayrollRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayrollRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async approveLeaveRequest(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveLeaveRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveLeaveRequest(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteEmployee(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPayrollRecords(): Promise<Array<PayrollRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayrollRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayrollRecords();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDepartments(): Promise<Array<Department>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartments();
            return result;
        }
    }
    async getEmployee(arg0: bigint): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeAttendance(arg0: bigint): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeAttendance(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeAttendance(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaveRequestsByEmployee(arg0: bigint): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveRequestsByEmployee(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveRequestsByEmployee(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayrollByEmployee(arg0: bigint): Promise<Array<PayrollRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayrollByEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayrollByEmployee(arg0);
            return result;
        }
    }
    async getPendingLeaveRequests(): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingLeaveRequests();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingLeaveRequests();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAttendance(arg0: bigint, arg1: Time, arg2: AttendanceStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, arg1, to_candid_AttendanceStatus_n28(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, arg1, to_candid_AttendanceStatus_n28(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async rejectLeaveRequest(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectLeaveRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectLeaveRequest(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitLeaveRequest(arg0: bigint, arg1: Time, arg2: Time, arg3: LeaveType, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLeaveRequest(arg0, arg1, arg2, to_candid_LeaveType_n30(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLeaveRequest(arg0, arg1, arg2, to_candid_LeaveType_n30(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async updateEmployee(arg0: bigint, arg1: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, to_candid_Employee_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, to_candid_Employee_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AttendanceRecord_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_EmployeeRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeRole): EmployeeRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_EmployeeStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeStatus): EmployeeStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Employee_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveRequest_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveRequest): LeaveRequest {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveStatus): LeaveStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveType): LeaveType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Employee | null {
    return value.length === 0 ? null : from_candid_Employee_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AttendanceStatus;
    date: _Time;
    employeeId: bigint;
}): {
    status: AttendanceStatus;
    date: Time;
    employeeId: bigint;
} {
    return {
        status: from_candid_AttendanceStatus_n19(_uploadFile, _downloadFile, value.status),
        date: value.date,
        employeeId: value.employeeId
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _LeaveStatus;
    endDate: _Time;
    employeeId: bigint;
    comments: string;
    leaveType: _LeaveType;
    startDate: _Time;
    reason: string;
}): {
    id: bigint;
    status: LeaveStatus;
    endDate: Time;
    employeeId: bigint;
    comments: string;
    leaveType: LeaveType;
    startDate: Time;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_LeaveStatus_n24(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        employeeId: value.employeeId,
        comments: value.comments,
        leaveType: from_candid_LeaveType_n26(_uploadFile, _downloadFile, value.leaveType),
        startDate: value.startDate,
        reason: value.reason
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EmployeeStatus;
    salary: bigint;
    joinDate: _Time;
    name: string;
    role: _EmployeeRole;
    email: string;
    phone: string;
    department: string;
}): {
    id: bigint;
    status: EmployeeStatus;
    salary: bigint;
    joinDate: Time;
    name: string;
    role: EmployeeRole;
    email: string;
    phone: string;
    department: string;
} {
    return {
        id: value.id,
        status: from_candid_EmployeeStatus_n8(_uploadFile, _downloadFile, value.status),
        salary: value.salary,
        joinDate: value.joinDate,
        name: value.name,
        role: from_candid_EmployeeRole_n10(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone,
        department: value.department
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    teacher: null;
} | {
    staff: null;
}): EmployeeRole {
    return "admin" in value ? EmployeeRole.admin : "teacher" in value ? EmployeeRole.teacher : "staff" in value ? EmployeeRole.staff : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    halfDay: null;
} | {
    present: null;
} | {
    late: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "halfDay" in value ? AttendanceStatus.halfDay : "present" in value ? AttendanceStatus.present : "late" in value ? AttendanceStatus.late : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): LeaveStatus {
    return "pending" in value ? LeaveStatus.pending : "approved" in value ? LeaveStatus.approved : "rejected" in value ? LeaveStatus.rejected : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sick: null;
} | {
    annual: null;
} | {
    maternity: null;
} | {
    casual: null;
}): LeaveType {
    return "sick" in value ? LeaveType.sick : "annual" in value ? LeaveType.annual : "maternity" in value ? LeaveType.maternity : "casual" in value ? LeaveType.casual : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): EmployeeStatus {
    return "active" in value ? EmployeeStatus.active : "inactive" in value ? EmployeeStatus.inactive : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaveRequest>): Array<LeaveRequest> {
    return value.map((x)=>from_candid_LeaveRequest_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n6(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): _EmployeeRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeStatus): _EmployeeStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_Employee_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): _Employee {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_LeaveType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveType): _LeaveType {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: EmployeeStatus;
    salary: bigint;
    joinDate: Time;
    name: string;
    role: EmployeeRole;
    email: string;
    phone: string;
    department: string;
}): {
    id: bigint;
    status: _EmployeeStatus;
    salary: bigint;
    joinDate: _Time;
    name: string;
    role: _EmployeeRole;
    email: string;
    phone: string;
    department: string;
} {
    return {
        id: value.id,
        status: to_candid_EmployeeStatus_n34(_uploadFile, _downloadFile, value.status),
        salary: value.salary,
        joinDate: value.joinDate,
        name: value.name,
        role: to_candid_EmployeeRole_n1(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone,
        department: value.department
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): {
    admin: null;
} | {
    teacher: null;
} | {
    staff: null;
} {
    return value == EmployeeRole.admin ? {
        admin: null
    } : value == EmployeeRole.teacher ? {
        teacher: null
    } : value == EmployeeRole.staff ? {
        staff: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    halfDay: null;
} | {
    present: null;
} | {
    late: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.halfDay ? {
        halfDay: null
    } : value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.late ? {
        late: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveType): {
    sick: null;
} | {
    annual: null;
} | {
    maternity: null;
} | {
    casual: null;
} {
    return value == LeaveType.sick ? {
        sick: null
    } : value == LeaveType.annual ? {
        annual: null
    } : value == LeaveType.maternity ? {
        maternity: null
    } : value == LeaveType.casual ? {
        casual: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == EmployeeStatus.active ? {
        active: null
    } : value == EmployeeStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
